### ISSUE TITLE
Unable to select a new search area within the current buffer graphic

### ISSUE THREAD

**Issue by karmstro77** [SpatialAgent/local-perspective#17]
I am attempting to click on the map to generate a new buffer but if my area of interest is within the existing buffer graphic, the app will not update. It only works if i select a location outside of the buffer graphic.

![image](https://cloud.githubusercontent.com/assets/6819070/5494427/42a71428-86c2-11e4-9fd6-42c58eb2c0f0.png)

**Comment by SpatialAgent** [comment]
Updated code to resolve issue in next release.
