### ISSUE TITLE
Reordering Widgets

### ISSUE THREAD

**Issue by MKellyEsri** [SpatialAgent/local-perspective#20]
Is it possible to reorder the widgets in this template? If not, could you give me some guidance as to what would be required code wise to implement this?

**Comment by SpatialAgent** [comment]
@MKellyEsri The order of widgets is based on the order of the layers in the web map.  Is there something specific you are looking for?

**Comment by MKellyEsri** [comment]
Apologies, I intended to raise this on the <a href="https://github.com/Esri/Viewer">basic viewer template</a>. I'm combining aspects from both templates which requires a reorder of the widgets (on the basic viewer template). Sorry for the mixup and thanks for your help - you are welcome to close this.
