### ISSUE TITLE
Names of Individual Points

### ISSUE THREAD

**Issue by anjaliintern** [SpatialAgent/local-perspective#32]
I am attempting to use this application to map alcohol distributors in Minnesota. However, when I add my layer, each individual point comes up with the same name. The specific name and address comes up once clicked on, but I've seen many other Local Perspective maps that don't have this issue.

![GitHub_Image](https://user-images.githubusercontent.com/51382478/58907510-f77e9400-86d3-11e9-9b34-559f5a92431b.PNG)

**Comment by SpatialAgent** [comment]
@anjaliintern I think, if you configure the popup for the layer in the webmap and set the title to the appropriate field, the local perspective app will display that field.
