### ISSUE TITLE
Proxy isn't working 

### ISSUE THREAD

**Issue by chclose** [SpatialAgent/local-perspective#34]
Hi there,

I wasen't able to get the proxy to work when using a private webmap.  Line 93 in the main.js file seems to imply the proxy is not working yet?

https://github.com/SpatialAgent/local-perspective/blob/af7721a957cb18c7e8288e94cfc9c86f3782a5f0/js/main.js#L93

However, I was able to get the proxy working by adding the following lines of code:

        urlUtils.addProxyRule({
          urlPrefix: "www.arcgis.com",
          proxyUrl: this.config.proxyurl
        });

under this line of code:
https://github.com/SpatialAgent/local-perspective/blob/af7721a957cb18c7e8288e94cfc9c86f3782a5f0/js/template.js#L274

Is there code missing or is something else not working right?

**Comment by SpatialAgent** [comment]
The proxy included with the app is a PHP proxy. You will need to configure your server for PHP or use a different proxy.

**Comment by chclose** [comment]
Thanks for your reply.  Can you please update the readme file to indicate this then please?  As it stands, the help doc (line 50) only states the generic "use a proxy" then links to the Javascript help page on proxys that points to the esri resource proxy on github for all 3 (.net, php, java).  At no point does it say, must use or only supports the php proxy.

Simply adding the proxy.php file in the template zip file is not enough.

Thanks

**Comment by SpatialAgent** [comment]
You can use any proxy you want (.NET,  Java, PHP or even your own). If you don't need to use a proxy, you can comment the line out. The PHP proxy is only included as a sample.

**Comment by chclose** [comment]
Would still be helpful if that were noted in the help aka "we've included a sample php proxy..."

**Comment by AmrEldib** [comment]
Hi @SpatialAgent 
I've been working with @chclose on this issue as part of an Esri Canada support case.

We've configured the template to use a proxy by setting the value of `proxyurl` to `/proxy/proxy.ashx` (which is a .NET proxy set up on the same IIS).
However, a secured webmap hosted on ArcGIS Online is still inaccessible. The user is met with a login dialog.
Inspecting traffic to Online via the browser's DevTools shows that requests aren't prefixed with the proxy URL.

After some troubleshooting, I found that changes to the `template.js` file are needed.
One of two types of changes is needed.
1. set `esriConfig.defaults.io.alwaysUseProxy` to `true`.
Or, 
2. Add a proxy rule right after the [`alwaysUseProxy` line](https://github.com/SpatialAgent/local-perspective/blob/af7721a957cb18c7e8288e94cfc9c86f3782a5f0/js/template.js#L274). A proxy rule would be something like:
```js
        urlUtils.addProxyRule({
          urlPrefix: "www.arcgis.com",
          proxyUrl: this.config.proxyurl
        });
```

This suggests that simply configuring the template to use a proxy isn't enough. This is why @chclose brought up the [ToDo line](https://github.com/SpatialAgent/local-perspective/blob/af7721a957cb18c7e8288e94cfc9c86f3782a5f0/js/main.js#L93). There's a section in the `main.js` file that is commented out that adds proxy rules.

The question is: can the template use a proxy without the code modifications we've made?
If so, why do you think it didn't in our case?

Thank you!

**Comment by SpatialAgent** [comment]
Thanks @AmrEldib @chclose. I'll modify the documentation to reflect that you need to make changes to the proxy, if you plan to use a proxy on your own server.
