### ISSUE TITLE
Mismatch Numbering

### ISSUE THREAD

**Issue by anjaliintern** [SpatialAgent/local-perspective#35]
The numbering on my map doesn't match the numbering in the column. This has not happened on previous projects with Local Perspective 
![Nalaxone_Mapping](https://user-images.githubusercontent.com/51382478/62786799-f7f72a80-ba88-11e9-8e5a-8ec783a15862.PNG)

**Comment by SpatialAgent** [comment]
@anjaliintern can you make sure points 1, 2 and 3 are not on top of each other?

**Comment by anjaliintern** [comment]
They are very close together but should have different addresses. It is not a huge problem but it concerned me.

**Comment by SpatialAgent** [comment]
@anjaliintern I suspect 3, is obscuring 2 and 1. If they aren't coincident, you should be able to see them when you zoom in.
